steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/mercurial-song-435220-a6/shivam-100964258/app:${SHORT_SHA}'
    - '.'

# Step 2: Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'push'
    - 'us-central1-docker.pkg.dev/mercurial-song-435220-a6/shivam-100964258/app:${SHORT_SHA}'

# Step 3: Deploy the container to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'shivam-100964258-service'
    - '--image'
    - 'us-central1-docker.pkg.dev/mercurial-song-435220-a6/shivam-100964258/app:${SHORT_SHA}'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'

# Options
options:
  logging: REGIONAL_USER_OWNED_BUCKET
