steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/mercurial-song-435220-a6/shivam-100964258/app:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/mercurial-song-435220-a6/shivam-100964258/app:latest'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'shivam-100964258-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/mercurial-song-435220-a6/shivam-100964258/app:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'

options:
  logging: CLOUD_LOGGING_ONLY  # Logs only in Cloud Logging

images:
  - 'us-central1-docker.pkg.dev/mercurial-song-435220-a6/shivam-100964258/app:latest'

