steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'northamerica-northeast2-docker.pkg.dev/assignment-2-gcp-pipelines/shivam-100964258/$REPO_NAME:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'northamerica-northeast2-docker.pkg.dev/assignment-2-gcp-pipelines/shivam-100964258/$REPO_NAME:$COMMIT_SHA']

images:
  - 'northamerica-northeast2-docker.pkg.dev/assignment-2-gcp-pipelines/shivam-100964258/$REPO_NAME:$COMMIT_SHA'
